#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: TrustID
  description: Decentralized Identity solution compatible with different Hyperledger platforms.
  homepage: https://wiki.hyperledger.org/display/fabric
  default_branch: master
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
